### PR TITLE
Corrected error in second answer

### PR DESCRIPTION
**Pull request by Amirmohammadomidi**

### CODE REVIEW

**Comment by martiny76** [comment]
Thanks

**Comment by Amirmohammadomidi** [comment]
Output should be like this. Figured out it's not a big deal, therefore, I haven't changed it. 
image

**Comment by martiny76** [comment]
It is okay. You can change it. That's not a problem at all. And after that,
you can do a new pull request again.

**Comment by Amirmohammadomidi** [comment]
Great, many thanks.

**Comment by martiny76** [comment]
You're welcome.

**Pull request merged**
